language: python
sudo: required
dist: trusty
python: "3.5"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y p7zip-full
install:
  - pip install twine
# command to run tests
script: ./repackage.sh
